name: CI
on:
  push:
    branches:
      - main
      - beta
      - alpha
  pull_request:
    branches:
      - main
      - beta
      - alpha

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2

      - run: npm ci

      - run: npx nx workspace-lint
      - run: if ! npx nx format:check ; then echo "Format check failed. Please run 'npx nx format:write'."; fi
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3

      - name: Release
        if: ${{ success() && (github.event_name != 'pull_request' || github.event.action == 'closed' && github.event.pull_request.merged == true) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx nx affected --target release --output-style stream
